App info plus cleanup
holochain/hc-state-cli-node pull request #7
Opened 2021-05-27 14:35 UTC by JettTech

Combines prs #5 and #6 with some cleanup and bumps holochain-conductor-api to v0.0.4

2021-05-27 15:46 UTC, zippy requested changes
I tested appInfo and it looks good.
However when I tried -s (dumpState) I noticed that that fails now, and it would be good to have that working too while we are doing clean up.  Can you look into that?

2021-06-02 11:05 UTC, peeech requested changes
1. If you look at github there's a lot of whitespace formatting issues. Might be nice to stick to standard.js formatting.
2. README.md should probably be updated
3. It might be nice to catch() errors produced by async function `call_admin_port()`, otherwise you get `Unhandled promise rejections`

2021-06-03 15:23 UTC, zippy approved these changes
Woot!

2021-06-03 15:23 UTC, zippy commented on README.md
> +            hc-state s "['hC0kqcfqvJ8krBR0bNnPsmLtFiEiMOHM0fX+U8FW+ROc7P10tUdc','hCAkcIRv7RZNVg8FWc6/oJZo04dZTXm7JP6tfMk3RptPY02cBQac']
```suggestion
            hc-state s "['hC0kqcfqvJ8krBR0bNnPsmLtFiEiMOHM0fX+U8FW+ROc7P10tUdc','hCAkcIRv7RZNVg8FWc6/oJZo04dZTXm7JP6tfMk3RptPY02cBQac']"
```

2021-06-03 23:36 UTC, merged